# Generated by Django 2.2 on 2021-09-12 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Treasures', '0004_hint'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasure',
            name='map_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
